[bot]
alttoken = "Alt Token Here"
maintoken = "Main Token Here"
altprefix = "au!"
mainprefix = "au?"
owner = "Main Name Here e.x:YourName#0000"
botname = "Alt Token Name Here e.x:Iambot"

[setup]
default = "Awesome Code"
